# Numpy 

<!-- # why to use Numpy over list :

1.Efficient Array Operations: 
2.Element-wise Operations: 
3.Mathematical Functions: 
4.Linear Algebra: 
5.Random Number Generation: 
6.Data Manipulation: 
7.Interoperability: 
8.Memory Efficiency: 
 -->

In [1]:
import numpy as np

## Basics

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)

print(b.shape)

b.ndim
# no.of dimension like 1d,2d,3d

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)


3

In [12]:
b.reshape(9,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
b.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Accessing / changing specific elements, row, columns etc.

In [18]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
# i want 0th row .
a[0,]

array([1, 2, 3, 4, 5, 6])

In [21]:
# i want 1st row.
a[1,]

array([ 7,  8,  9, 10, 11, 12])

In [25]:
a[1,5]
# it will give 1st row and 5th column

12

In [26]:
# i want value from 0th row and 4th column
a[0,4]

5

In [23]:
# i want all rows and 1st column
a[:,1]

array([2, 8])

In [24]:
# i want all rows and 4th column.
a[:,4]
# leave it blank if you need all

array([ 5, 11])

In [28]:
# i want 2,3,8,9
a[:,1:3]
#  a[row start point : row end point , column start point : column end point]

array([[2, 3],
       [8, 9]])

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
# i want 1,7,5,11
a[:,:5:4]
#  a[row start point : row end point : step , column start point : column end point : step]

array([[ 1,  5],
       [ 7, 11]])

In [33]:
# i want 9
a[1,2]

9

In [35]:
# i want to change that 9 with 99
a[1,2]=99
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8, 99, 10, 11, 12]])

In [38]:
# i want change the 0th row by multiplying it with 10

a[0,:]=a[0]*10

a

array([[100, 200, 300, 400, 500, 600],
       [  7,   8,  99,  10,  11,  12]])

In [39]:
# i want 1row squared

a[1,:] = a[1]**2

a

array([[ 100,  200,  300,  400,  500,  600],
       [  49,   64, 9801,  100,  121,  144]])


### slicing of 3D array

In [45]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
# i want 5 and 6
a[1,:,0]

# a[[1st]list all the rows and 0th column]

array([5, 7])

In [48]:
# i want 6
a[1,0,1]

6

In [65]:
# i want 1,3,5,7

a[:,:,0]

array([[1, 3],
       [5, 7]])

In [66]:
# i want 2,4,6,8
a[:,:,1]

array([[2, 4],
       [6, 8]])

In [67]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [74]:
# i want 1,3,6,8
[a[0,0,0],a[0,1,0],a[1,0,1],a[1,1,1]]

[1, 3, 6, 8]

In [77]:
# Slicing to extract the values 2, 4, 6, and 8
a[:, :, 1].flatten()
# flatten = Return a copy of the array collapsed into one dimension.
# by default it will go through all the row.

array([2, 4, 6, 8])

In [82]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [81]:
a.flatten('f')

array([1, 5, 3, 7, 2, 6, 4, 8])

In [83]:
a.flatten('c')

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
a.flatten('a')

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
a.flatten('k')

array([1, 2, 3, 4, 5, 6, 7, 8])

## Initializing the data set



In [88]:
np.zeros(4)

array([0., 0., 0., 0.])

In [89]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [92]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])