In [2]:
## numpy
import numpy as np

In [5]:
lst=[1,2,3,4]
arr=np.array(lst)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [13]:
# 2 dimensional
arr1=np.array([[1,2,3],[4,5,6]])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# 2 dimensions. 2 rows 3 column.  2*3=6.
arr1.shape

(2, 3)

In [16]:
# reshape 3 rows 2 column.
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# 1 row 6 column.
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [18]:
# 6 rows and 1 column.
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [5]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [7]:
dict={'a':101,'b':202}

In [8]:
dict

{'a': 101, 'b': 202}

In [19]:
# try with dictionary values
arr3=np.array({'a':101,'b':202,'c':303,'d':404})

In [20]:
arr3

array({'a': 101, 'b': 202, 'c': 303, 'd': 404}, dtype=object)

In [21]:
arr1.dtype # int 32 means 32 bit.

dtype('int32')

In [22]:
### creating array from scratch
# arange=array + range.

In [25]:
arr6=np.arange(1,10,2)
print(arr6)
len(arr6)

[1 3 5 7 9]


5

In [27]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [32]:
np.arange(1,20,2)

# total elements=10 it can be 2*5,5*2.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [4]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [27]:
print(np.array(range(1,20,2)))
print(np.arange(1,20,2))

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [43]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# equally spacing 1 to 20 elements in 40 steps.
# linspace is differ from range function.
# linspace means linearly spaced.
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [6]:
np.linspace(2,21,20)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21.])

In [53]:
np.linspace(1,10.5,20)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [56]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
np.ones((5,2,8))
# 5 elements
# 2 rows
# 8 columns

# for 3 dimensonal array [[[ ]]] is used.

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [61]:
np.ones((5,2,8)).reshape(5,8,2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
np.ones((5,2,8)).reshape(5,4,4)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [63]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
5+ np.ones((3,5))
# it will add 5 in every elements.

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
np.eye(6).reshape(4,9)
# diogonal element, eye for identity.
# total elemets are 36.

array([[1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.eye(6).reshape(9,4)

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [68]:
# generate random number in uniform distribution.
# it will print any random number with 2 rows and 3 column.
np.random.rand(2,3)

array([[0.38904912, 0.08980708, 0.62284907],
       [0.61388257, 0.37274501, 0.96496027]])

In [70]:
# normal distribution.
print('random number following a normal distribution with mean=0 and std=1')
print(np.random.randn(5,3))

random number following a normal distribution with mean=0 and std=1
[[-0.1525069   1.06091543  1.16581667]
 [-1.45692573 -2.59418777 -0.84355367]
 [-0.47903479  1.57159055 -0.02919834]
 [-1.08758013 -0.82873418 -1.64827644]
 [-0.16542637  0.03668768 -0.54461523]]


In [35]:
# print random number from 1 to 100.
np.random.randint(1,100)

59

In [72]:
np.random.randint(1,100,10) # it will print random number from 1 to 100 but only 10 elements.

array([34, 53, 14, 18, 11, 36, 10, 35, 94, 62])

In [73]:
np.random.randint(1,100,(4,4)) # it will print 4*4=16 elements.

array([[ 8, 73, 34, 73],
       [51, 70, 61, 21],
       [ 5, 78, 80, 42],
       [86, 59, 36, 81]])

In [74]:
arr=np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# slicing
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [81]:
arr[-1]

10

In [84]:
arr[-1:7] # it will not give ouput.

array([], dtype=int32)

In [83]:
arr[-1:7:-1]
# negative indexing from backend.

array([10,  9,  8])

In [87]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [36]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [37]:
arr1

array([[67, 36, 65, 25],
       [11, 52, 69, 23],
       [36, 34, 83, 72],
       [44,  6, 24, 13],
       [73, 47, 60, 24]])

In [38]:
arr1[0:3,0:3]
# 0:3 for 3 rows 
# next 0:3 for columns

array([[67, 36, 65],
       [11, 52, 69],
       [36, 34, 83]])

In [39]:
arr1[3:,1:4]
# i want from 3 rd row and second column to the end.


array([[ 6, 24, 13],
       [47, 60, 24]])

In [40]:
arr1[2:4,1:3]
# i want 2 and 3 rd row
# i want 2nd and 3rd column.

array([[34, 83],
       [ 6, 24]])

In [41]:
arr1[-3:-1,-3:-1]

array([[34, 83],
       [ 6, 24]])

In [42]:
arr1

array([[67, 36, 65, 25],
       [11, 52, 69, 23],
       [36, 34, 83, 72],
       [44,  6, 24, 13],
       [73, 47, 60, 24]])

In [43]:
# 19 85 83 31

arr1[2:4,0::3]

array([[36, 72],
       [44, 13]])

In [104]:
## universal functons.

arr1=np.random.randint(2,100,20).reshape(5,4)
arr2=np.random.randint(4,200,20).reshape(5,4)

In [105]:
arr1

array([[20, 17, 89, 79],
       [98, 32, 25, 94],
       [30, 26, 52, 75],
       [ 2, 59, 48, 17],
       [53, 78, 81, 74]])

In [106]:
arr2

array([[ 77,  13, 158,  19],
       [ 68,  67, 126, 184],
       [ 71,  15,  13,  41],
       [139, 156,  47,  44],
       [ 24,  15, 186,  43]])

In [107]:
arr1+arr2

array([[ 97,  30, 247,  98],
       [166,  99, 151, 278],
       [101,  41,  65, 116],
       [141, 215,  95,  61],
       [ 77,  93, 267, 117]])

In [108]:
np.exp(arr2)

array([[2.75851345e+33, 4.42413392e+05, 4.15458971e+68, 1.78482301e+08],
       [3.40427605e+29, 1.25236317e+29, 5.26144118e+54, 8.13176221e+79],
       [6.83767123e+30, 3.26901737e+06, 4.42413392e+05, 6.39843494e+17],
       [2.32773204e+60, 5.62262575e+67, 2.58131289e+20, 1.28516001e+19],
       [2.64891221e+10, 3.26901737e+06, 6.00860471e+80, 4.72783947e+18]])

In [109]:
np.log10(arr1)

array([[1.30103   , 1.23044892, 1.94939001, 1.89762709],
       [1.99122608, 1.50514998, 1.39794001, 1.97312785],
       [1.47712125, 1.41497335, 1.71600334, 1.87506126],
       [0.30103   , 1.77085201, 1.68124124, 1.23044892],
       [1.72427587, 1.8920946 , 1.90848502, 1.86923172]])

In [44]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# broadcasting  after 2nd element every element is 1000.
arr1[2:]=1000

In [46]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [3]:
i=2*3+7
print(i)
print(id(i))

13
1922047371952


In [4]:
p=9+4
print(p)
print(id(p))

13
1922047371952


In [5]:
l=[1,2,3,4]
print(l)
print(id(l))

[1, 2, 3, 4]
1922129823808


In [8]:
t=(1,2,3,4)
print(t)
print(id(t))

t2=(1,2,3,4)
print(id(t2))

(1, 2, 3, 4)
1922129739104
1922129738784


In [7]:
pritam=[1,2,3,4]
print(pritam)
print(id(pritam))

[1, 2, 3, 4]
1922129627584
