In [ ]:
## pandas..
# 1.pandas dataframe
# 2.pandas series
# 3.pandas basic operation.

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
## creating a dataframe.

pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],
             columns=['column1','column2','column3','column4'])

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [11]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],
             columns=['column1','column2','column3','column4'])

In [13]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [14]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df.head(2)
# it will give top 2 records

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [19]:
df.tail(3)
# it will give last 3 records.

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [20]:
df.describe()
# it will be used only with numerical data.

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [21]:
df[['column1','column2','column3']]
# exctract only 3 column.

column1  column2  column3
row1        0        1        2
row2        4        5        6
row3        8        9       10
row4       12       13       14
row5       16       17       18

In [24]:
df[['column1']]

column1
row1        0
row2        4
row3        8
row4       12
row5       16

In [23]:
type(df[['column1']])

pandas.core.frame.DataFrame

In [25]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32

In [26]:
type(df['column1'])

pandas.core.series.Series

In [28]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [29]:
# location parameter.
df.loc[['row1','row3']]

column1  column2  column3  column4
row1        0        1        2        3
row3        8        9       10       11

In [33]:
## with the help of indexing and slicing
#  for indexing we use iloc instead of loc.

df.iloc[0:3,0:2]

# 0:3 from 0th row to the 3rd row.
# from 0th column to 2nd column.

column1  column2
row1        0        1
row2        4        5
row3        8        9

In [35]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [36]:
df.iloc[2:4,1:3]

column2  column3
row3        9       10
row4       13       14

In [37]:
df.iloc[2:4,1:3].values
# it will only values in array

array([[ 9, 10],
       [13, 14]])

In [39]:
df.iloc[2:4,1:3].values.reshape(4,1) # we can reshape the values.

array([[ 9],
       [10],
       [13],
       [14]])

In [38]:
np.nan # it means null value.

nan

In [3]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=['row1','row2'],
             columns=['column1','column2','column3'])
# here we have created another df and used one null value.

df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4

In [44]:
df.isnull()# it will give True for 'nan' value.

column1  column2  column3
row1    False     True    False
row2    False    False    False

In [4]:
df.isnull().sum()
# it will give total number of nan values.

column1    0
column2    1
column3    0
dtype: int64

In [9]:
print(df.isnull().sum())


print(df.isna().sum())
# it is same as isnull

column1    0
column2    1
column3    0
dtype: int64
column1    0
column2    1
column3    0
dtype: int64


In [10]:
df.isna().sum()
# it is same as isnull

column1    0
column2    1
column3    0
dtype: int64

In [48]:
type(np.nan)

float

In [49]:
df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4

In [12]:
df['column1'].value_counts()
# value counts only applied for series.


1    2
Name: column1, dtype: int64

In [58]:
df['column1'].unique()
# it will give unique values in the perticular column.

array([1], dtype=int64)

In [59]:
df['column1'].nunique()
# it will give number of unique values in that column

1

In [60]:
df = pd.DataFrame({'A': [4, 5, 6], 'B': [4, 1, 1]})

In [61]:
df

A  B
0  4  4
1  5  1
2  6  1

In [66]:
df['A'].unique()

array([4, 5, 6], dtype=int64)

In [67]:
df['A'].nunique()
# no.of unique values

3

In [68]:
df['B'].unique()

array([4, 1], dtype=int64)

In [69]:
df['B'].nunique()

2

In [70]:
df.nunique(axis=0)# axis=0 check unique values for all row index
# when axis = 0 it will go through all data in one single shot and treat it as like one axis.

A    3
B    2
dtype: int64

In [71]:
df.nunique(axis=1)# unique values in every row index.
# when axis = 1 it will treat every row as a new axis

0    1
1    2
2    2
dtype: int64

In [72]:
df

A  B
0  4  4
1  5  1
2  6  1

In [74]:
df['A'].nunique()

3

In [75]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],
             columns=['column1','column2','column3','column4'])

In [76]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [79]:
df['column2']>5
# it will give result in true false 

row1    False
row2    False
row3     True
row4     True
row5     True
Name: column2, dtype: bool

In [78]:
df[df['column2']>5]
# it will give actual actual values that are >5.
# take out values that are greater than 5.

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [82]:
df[df['column4']>5]

column1  column2  column3  column4
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [84]:
df['column4']>5

row1    False
row2     True
row3     True
row4     True
row5     True
Name: column4, dtype: bool

In [85]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [86]:
df.to_csv('test.csv')
# to save into the csv file.

In [ ]:
df

In [87]:
df1=pd.read_csv('test.csv')

In [88]:
df1

Unnamed: 0  column1  column2  column3  column4
0       row1        0        1        2        3
1       row2        4        5        6        7
2       row3        8        9       10       11
3       row4       12       13       14       15
4       row5       16       17       18       19

In [89]:
df.to_csv('test.csv',index=False)# it will remove row indexing.

In [90]:
df1=pd.read_csv('test.csv')
df1

column1  column2  column3  column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [91]:
df.to_excel('test.xlsx')
# to save as excel file

In [92]:
pd.read_excel('test.xlsx')
# to read from excel file

Unnamed: 0  column1  column2  column3  column4
0       row1        0        1        2        3
1       row2        4        5        6        7
2       row3        8        9       10       11
3       row4       12       13       14       15
4       row5       16       17       18       19

In [97]:
# with json,

In [14]:
data='{"employee_name":"krish","email":"krish@gmail.com","job_profile":[{"title":"team_lead","role":"developer"}]}'

In [15]:
data

'{"employee_name":"krish","email":"krish@gmail.com","job_profile":[{"title":"team_lead","role":"developer"}]}'

In [18]:
pd.read_json(data,orient='column')
# in orient section we can use 'column' or 'row'.

employee_name            email                                  job_profile
0         krish  krish@gmail.com  {'title': 'team_lead', 'role': 'developer'}

In [19]:
pd.read_json(data,orient='index')
# orient = index is another way to plot it.

0
employee_name                                          krish
email                                        krish@gmail.com
job_profile    [{'title': 'team_lead', 'role': 'developer'}]

In [20]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],
             columns=['column1','column2','column3','column4'])

In [21]:

df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [22]:
df.to_json()
# bydefault it will give result based on column

'{"column1":{"row1":0,"row2":4,"row3":8,"row4":12,"row5":16},"column2":{"row1":1,"row2":5,"row3":9,"row4":13,"row5":17},"column3":{"row1":2,"row2":6,"row3":10,"row4":14,"row5":18},"column4":{"row1":3,"row2":7,"row3":11,"row4":15,"row5":19}}'

In [23]:
df.to_json(orient="records")
# records will give result directly by column

'[{"column1":0,"column2":1,"column3":2,"column4":3},{"column1":4,"column2":5,"column3":6,"column4":7},{"column1":8,"column2":9,"column3":10,"column4":11},{"column1":12,"column2":13,"column3":14,"column4":15},{"column1":16,"column2":17,"column3":18,"column4":19}]'

In [24]:
df.to_json(orient="index")
# index will give result based on rows

'{"row1":{"column1":0,"column2":1,"column3":2,"column4":3},"row2":{"column1":4,"column2":5,"column3":6,"column4":7},"row3":{"column1":8,"column2":9,"column3":10,"column4":11},"row4":{"column1":12,"column2":13,"column3":14,"column4":15},"row5":{"column1":16,"column2":17,"column3":18,"column4":19}}'

In [26]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [27]:
df

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [28]:
df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [29]:
df.to_json(orient="records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"